export const UPDATE_AUTH = "UPDATE_AUTH";
export const LOGOUT = "LOGOUT";
export const TOGGLE_SHOWLOGIN = "TOGGLE_SHOWLOGIN";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST";
export const FETCH_REQUEST_AUTH = "FETCH_REQUEST_AUTH";
export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";
export const FETCH_ERROR_AUTH = "FETCH_ERROR_AUTH";

